demoproject_2/src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Improvements_Needed__c</fullName>
        <label>Improvements Needed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Comments__c</fullName>
        <label>Overall Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <label>Session_ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>What_was_the_session_like__c</fullName>
        <label>What did you like</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

demoproject_2/src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Session_ID__c</fullName>
        <displayFormat>S-{0000}</displayFormat>
        <inlineHelpText>ID of the session.</inlineHelpText>
        <label>Session_ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

demoproject_2/src/classes/FeedbackController.cls
public class FeedbackController {
    public Session__c s{get;set;}
    public Session__c sq;
    public String SessionId {get; set;}
    public Feedback__c f;
    public FeedbackController()
        {
        s=new Session__c();
        f=new Feedback__c();
        SessionId = '';
        }

        public String t1{get;set;}
        public String t2{get;set;}
        public String t3{get;set;}
       

    public PageReference cancel() {
     t1=null;
     t2=null;
     t3=null;
     SessionId =null;
     return null;
    }


    public pageReference savef() {
        sq=[select id from Session__c where Session_ID__c =: SessionId];
        
        f.name='feedback';
        f.Session_ID__c=SessionId;
        f.What_was_the_session_like__c=t1;
        f.Improvements_Needed__c=t2;
        f.Overall_Comments__c=t3;
        f.Session__c = sq.id;
        insert f;

        PageReference p = new PageReference('/feedback/FeedbackForm');
        return p;
}
}